### ISSUE TITLE
Color of nested rule with "&" in SCSS syntax

### ISSUE THREAD

**Issue by DNLHC** [simurai/duotone-dark-space-syntax#1]
When you use nesting in SCSS the color of selector has the same color as variables. It's kinda confuse me. I think it supose to be white as any other selectors.

<a href="http://imgur.com/TJjzcSc"><img src="http://i.imgur.com/TJjzcSc.jpg" title="source: imgur.com" /></a>

**Comment by simurai** [comment]
This is now fixed in the master Duo tone theme: https://github.com/simurai/duotone-syntax/commit/d7f1fb8ec33e15ec53da41315bd53a35ee2b28e3

Will eventually trickle down to this one too.
